version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - node6
      - node8
      - node10
jobs:
  node6:
    working_directory: ~/enju
    docker:
      - image: node:6.14.3
    steps:
      - checkout
      - run: npm install -g coffee-script nodeunit grunt-cli
      - run: npm install
      - run: grunt build
      - run: npm test

  node8:
    working_directory: ~/enju
    docker:
      - image: node:8.11.3
    steps:
      - checkout
      - run: npm install -g coffee-script nodeunit grunt-cli
      - run: npm install
      - run: grunt build
      - run: npm test

  node10:
    working_directory: ~/enju
    docker:
      - image: node:10.6.0
    steps:
      - checkout
      - run: npm install -g coffee-script nodeunit grunt-cli
      - run: npm install
      - run: grunt build
      - run: npm test
