version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - node6
      - node8
      - node10
      - node11
jobs:
  node6:
    working_directory: ~/enju
    docker:
      - image: node:6.16.0
    steps:
      - checkout
      - run: npm install -g grunt-cli
      - run: npm install
      - run: npm run build
      - run: npm test

  node8:
    working_directory: ~/enju
    docker:
      - image: node:8.15.0
    steps:
      - checkout
      - run: npm install -g grunt-cli
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: npm run coveralls

  node10:
    working_directory: ~/enju
    docker:
      - image: node:10.15.1
    steps:
      - checkout
      - run: npm install -g grunt-cli
      - run: npm install
      - run: npm run build
      - run: npm test

  node11:
    working_directory: ~/enju
    docker:
      - image: node:11.9.0
    steps:
      - checkout
      - run: npm install -g grunt-cli
      - run: npm install
      - run: npm run build
      - run: npm test
