version: 2.0
jobs:
  build:
    working_directory: ~/enju
    docker:
      - image: node:8.9.3
    steps:
      - checkout
      - run:
          name: "Trigger Jobs"
          command: |
            # a similar function will liekly get built in into the circleci cli
            function trigger_job() {
              job_name=$1
              curl -u ${CIRCLE_API_TOKEN}: \
                -d build_parameters[CIRCLE_JOB]=${job_name} \
                -d revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/your_org/your_project/tree/$CIRCLE_BRANCH
            }
            trigger_job build-node6
            trigger_job build-node8

  build-node6:
    working_directory: ~/enju
    docker:
      - image: node:6.12.3
    steps:
      - run: |
          npm install -g nodeunit grunt-cli
          npm install
          grunt build
          npm test

  build-node8:
    working_directory: ~/enju
    docker:
      - image: node:8.9.3
    steps:
      - run: |
          npm install -g nodeunit grunt-cli
          npm install
          grunt build
          npm test
