version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - node8
      - node10
      - node12
jobs:
  node8:
    working_directory: ~/enju
    docker:
      - image: node:8.16.0
    steps:
      - checkout
      - run: npm install -g grunt-cli
      - run: npm install
      - run: npm run build
      - run: npm test

  node10:
    working_directory: ~/enju
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run: npm install -g grunt-cli
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: npm run coveralls

  node12:
    working_directory: ~/enju
    docker:
      - image: node:12.0.0
    steps:
      - checkout
      - run: npm install -g grunt-cli
      - run: npm install
      - run: npm run build
      - run: npm test
