version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - node6
      - node8
      - node10
      - node11
jobs:
  node6:
    working_directory: ~/enju
    docker:
      - image: node:6.15.1
    steps:
      - checkout
      - run: npm install -g coffeescript nodeunit grunt-cli
      - run: npm install
      - run: npm run build
      - run: npm test

  node8:
    working_directory: ~/enju
    docker:
      - image: node:8.14.0
    steps:
      - checkout
      - run: npm install -g coffeescript nodeunit grunt-cli
      - run: npm install
      - run: npm run build
      - run: npm test

  node10:
    working_directory: ~/enju
    docker:
      - image: node:10.14.1
    steps:
      - checkout
      - run: npm install -g coffeescript nodeunit grunt-cli
      - run: npm install
      - run: npm run build
      - run: npm test

  node11:
    working_directory: ~/enju
    docker:
    - image: node:11.4.0
    steps:
    - checkout
    - run: npm install -g coffeescript nodeunit grunt-cli
    - run: npm install
    - run: npm run build
    - run: npm test
