version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - node6
      - node8
      - node9
jobs:
  node6:
    working_directory: ~/enju
    docker:
      - image: node:6.13.1
    steps:
      - checkout
      - run: npm install -g coffee-script nodeunit grunt-cli
      - run: npm install
      - run: grunt build
      - run: npm test

  node8:
    working_directory: ~/enju
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - run: npm install -g coffee-script nodeunit grunt-cli
      - run: npm install
      - run: grunt build
      - run: npm test

  node9:
    working_directory: ~/enju
    docker:
      - image: node:9.7.1
    steps:
      - checkout
      - run: npm install -g coffee-script nodeunit grunt-cli
      - run: npm install
      - run: grunt build
      - run: npm test
