version: 2.0
jobs:
  build:
    working_directory: ~/enju
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run:
          name: "Trigger Jobs"
          command: |
            # a similar function will liekly get built in into the circleci cli
            function trigger_job() {
              job_name=$1
              curl -u 00fd1badfa3a9ac5e39bcda4e32e52ddc54a17da: \
                -d build_parameters[CIRCLE_JOB]=${job_name} \
                -d revision=$CIRCLE_SHA1 \
                https://circleci.com/api/v1.1/project/github/kelp404/enju/tree/$CIRCLE_BRANCH
            }
            trigger_job build-node6
            trigger_job build-node8

  build-node6:
    working_directory: ~/enju
    docker:
      - image: node:6.12.3
    steps:
      - checkout
      - run: npm install -g coffee-script nodeunit grunt-cli
      - run: npm install
      - run: grunt build
      - run: npm test

  build-node8:
    working_directory: ~/enju
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run: npm install -g coffee-script nodeunit grunt-cli
      - run: npm install
      - run: grunt build
      - run: npm test
